/*
 * Position_m.h
 *
 *  Created on: 27 de mai de 2021
 *      Author: allan
 */

#ifndef INET_POSITION_M_H_
#define INET_POSITION_M_H_


#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class location;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry


namespace inet {

/**
 * Class generated from <tt>Location.msg:24</tt> by nedtool.
 * <pre>
 * class location extends TagBase
 * {
 *     double xPosition;
 *     double yPosition;
 * }
 * </pre>
 */
class location : public ::inet::TagBase
{
  protected:
    double xPosition;
    double yPosition;

  private:
    void copy(const location& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const location&);

  public:
    location();
    location(const location& other);
    virtual ~location();
    location& operator=(const location& other);
    virtual location *dup() const override {return new location(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getXPosition() const;
    virtual void setXPosition(double xPosition);
    virtual double getYPosition() const;
    virtual void setYPosition(double yPosition);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const location& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, location& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif /* INET_POSITION_M_H_ */
